receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4317

exporters:
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
