apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=  # base64 encoded value of "todo_db"
  POSTGRES_USER: dG9kb19hZG1pbgo=  # base64 encoded value of "todo_admin"
  POSTGRES_PASSWORD: YWRtaW4K  # base64 encoded value of "admin"
